apiVersion: alerts.monstorak.org/v1alpha1
kind: StorageAlert
metadata:
  name: nooba-storagealert
  namespace: storage-monitoring
spec:
  storage:
  - provider: "noobaa"
    version: "v1.0"
    namespace: "openshift-storage"
    serviceMonitor: "noobaa-mgr"
  prometheus:
    namespace: "openshift-monitoring"
    label: {"prometheus":"K8s"}